# Created by: kaushikdbg
# Last updated: 2025-05-02 10:30:00 UTC

name: 'Build, Scan, and Sign Docker Image with Direct WIF Authentication'

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ATTESTOR_ID: ${{ secrets.GCP_ATTESTOR_ID }}
  KEY_LOCATION: ${{ secrets.GCP_KEY_LOCATION }}
  KEYRING: ${{ secrets.GCP_KEYRING }}
  KEY_NAME: ${{ secrets.GCP_KEY_NAME }}
  KEY_VERSION: ${{ secrets.GCP_KEY_VERSION }}
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/artifact-scanning-repo/sample-image
  SERVICE: 'bin-auth-cloudrun'
  REGION: 'us-central1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    
    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation authentication
    
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' #actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud using Direct Workload Identity Federation'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2'
        with:
          workload_identity_provider: 'projects/751456426809/locations/global/workloadIdentityPools/github/providers/my-repo'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: 'Configure Docker for Artifact Registry'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      
      - name: 'Build Docker image'
        id: 'build'
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          
      - name: 'Push Docker image for scanning'
        run: |
          docker push ${{ env.IMAGE_NAME }}
          
      - name: 'Run vulnerability scan'
        id: 'scan'
        run: |
          SCAN_ID=$(gcloud artifacts docker images scan \
            ${{ env.IMAGE_NAME }} \
            --location us \
            --project=${{ env.PROJECT_ID }} \
            --quiet \
            --format="value(response.scan)")
          echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
          echo "Scan ID: $SCAN_ID"
      
      - name: 'Check severity of vulnerabilities'
        id: 'severity-check'
        run: |
          # Check only for HIGH vulnerabilities in package types other than OS
          HIGH_NON_OS=$(gcloud artifacts docker images list-vulnerabilities ${{ env.SCAN_ID }} \
            --format="json" | jq '[.[] | select(.vulnerabilityId | select(.effectiveSeverity == "CRITICAL" and .vulnerability.packageIssue.packageType != "OS" ))] ')
          echo "Total high vulnerabilities found: $(echo $HIGH_NON_OS | jq '. | length')"

          
          if [ -n "$HIGH_NON_OS" ]; then
            echo "Failed vulnerability check for HIGH level in non-OS packages"
            exit 1
          else
            echo "No HIGH vulnerability found, congrats!"
          fi
         
      
      - name: 'Retag Docker image'
        if: success()
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:good
      
      - name: 'Push tagged Docker image'
        if: success()
        run: |
          docker push ${{ env.IMAGE_NAME }}:good
      
      - name: 'Sign the image (Create attestation)'
        if: success()
        run: |
          # Get the image digest for the container
          DIGEST=$(gcloud container images describe ${{ env.IMAGE_NAME }}:good \
            --format='get(image_summary.digest)')
          gcloud components install beta --quiet
          
          # Create attestation using the image digest
          gcloud beta container binauthz attestations sign-and-create \
            --artifact-url="${{ env.IMAGE_NAME }}@${DIGEST}" \
            --project="${{ env.PROJECT_ID }}" \
            --attestor="${{ env.ATTESTOR_ID }}" \
            --attestor-project="${{ env.PROJECT_ID }}" \
            --keyversion-project="${{ env.PROJECT_ID }}" \
            --keyversion-location="${{ env.KEY_LOCATION }}" \
            --keyversion-keyring="${{ env.KEYRING }}" \
            --keyversion-key="${{ env.KEY_NAME }}" \
            --keyversion="${{ env.KEY_VERSION }}" \
            --quiet
      
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          project_id: '${{ env.PROJECT_ID }}'
          region: '${{ env.REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          image: '${{ env.IMAGE_NAME }}:good'
          flags: '--binary-authorization=default'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
